### ISSUE TITLE
Possibility for default "Spoiler" button style's be Bootstrap

### ISSUE THREAD

**Issue by jtsimoes** [am1cable/nodebb-plugin-simple-spoiler#1]
I love this plugin! It's very simple but very very functional and effective. And no bugs found! Good job!

I will only ask if you could add the Bootstrap class `.btn` (for example, `.btn-default`) to the _"Spoiler"_ button to make a little more beautiful with the Persona theme.
Then, people can customize it a little bit more advanced on the Admin Control Panel>Appearance>Custom CSS/LESS Content field, by adding `!important` declarations to `spoiler-control` and `spoiler-wrapper` classes.

Thanks!

**Comment by 4m2c4bl3** [comment]
added this in to 0.2.2
