### ISSUE TITLE
Listings with * inside spoilers

### ISSUE THREAD

**Issue by Jey-Cee** [am1cable/nodebb-plugin-simple-spoiler#4]
- **NodeBB version:** 1.12.2

- **Database type:** mongo
- **Database version:** 3.6.12

- **Plugin:** https://github.com/am1cable/nodebb-plugin-simple-spoiler

      1. Create Spoiler and add listing with *
	
- **What happened instead:**
The spoiler works normaly, but the footer is shown twice and it is not possible to edit any post on the thread. The menu with the three dots is empty.

**Comment by Antosik** [comment]
@Jey-Cee, can you provide a full example of an errored markdown, please?

---
UPD. Looks like this works fine on NodeBB v1.16.x
<details><summary>Example</summary>
<img src="https://user-images.githubusercontent.com/4852791/104885267-d20dcf00-5978-11eb-8384-dbe3f2f4a8a2.png" />
</details>

**Comment by Jey-Cee** [comment]
@Antosik thank you for your reply. We've recently updated our forum to 1.16.1 and no this works well.
Before we updated i have done some tests with a new installation of 1.12.x. During this tests it was also working as expected and i wasn't able to reproduce this behaivior. 
So i think we can close this issue.
